dev = false

[log]
level = "info"
format = "text"
add_source = false

[server]
addr = ":8086"
admin_password = "supersecretpassword"
public_url = "http://localhost:8086"

[database]
host = "localhost" # replace with db in case you run with the compose.yml
port = 5432
username = "campfire-auth"
password = "password"
database = "campfire-auth"
ssl_mode = "disable"

[campfire]
every = "2s"
burst = 10
max_retries = 3

[notifications]
enabled = true
webhook_url = "https://discord.com/api/webhooks/<ID>/<TOKEN>"
